name: Test Code
on:
  pull_request:
  push:
    branches:
      - develop/*
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  Validate-Changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Dependencies
        run: npm install
      - name: Test Lint
        run: npm run lint
      - name: Test coverage
        run: npm run test
  QA-Deploy:
    needs: Validate-Changes
    environment:
      name: 'QA'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Dependencies
        run: npm install
      - name: set Homepage
        run: npm run setHomepage
      - name: build
        run: CI=false npm run build
      - name: deploy
        run: netlify deploy -p --auth ${{secrets.NETLIFY_AUTH_TOKEN}} --site ${{secrets.NETLIFY_SITE_ID}}
      


